// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    id_brand: "",
    name_req_: "",
    slug_req_: "",
    slug_req_update: "",
    name_req_update: ""
  },
  environment: {
    url: "https://api.practicesoftwaretesting.com"
  }
});

export default function () {
  postman[Request]({
    name: "get all brands",
    id: "4c52a25d-83bf-4f8c-9ffd-760f3cc4160d",
    method: "GET",
    address: "{{url}}/brands",
    post(response) {
      pm.test("Status code is 200", function () {
        pm.response.to.have.status(200);
      });
      pm.test("Response time is less than 250ms", function () {
        pm.expect(pm.response.responseTime).to.be.below(250);
      });
    }
  });



  //declarer vairbale random 
  postman[Request]({
    name: "add brands",
    id: "9393452b-259e-4a3c-b779-5f788d889db1",
    method: "POST",
    address: "{{url}}/brands",
    data: '{\r\n  "name": "{{name_req_}}",\r\n  "slug": "{{slug_req_}}"\r\n}',
    //data: JSON.stringify({ name: name_req, slug: slug_req }),
    headers: {
      "Content-Type": "application/json",
      "Accept": "application/json"
    },
    pre() {
      let name_req = "name"
      let slug_req = "Slug" + Math.floor(Math.random() * (50000 - 1000 + 1)) + 1000
      pm.collectionVariables.set("name_req_", name_req)
      pm.collectionVariables.set("slug_req_", slug_req)
    },
    post(response) {
      pm.test("Status code is 201", function () {
        pm.response.to.have.status(201);
      });
      pm.test("Response 2 time is less than 250ms", function () {
        pm.expect(pm.response.responseTime).to.be.below(250);
      });
      pm.test("check body request", function () {
        let res_body = pm.response.json();
        let req_body = JSON.parse(pm.request.body.raw);
        pm.expect(res_body.name).to.equal(req_body.name);
        pm.expect(res_body.slug).to.equal(req_body.slug);
        pm.collectionVariables.set("id_brand", res_body.id)
        //console.log("====>" + pm.collectionVariables.get("id_brand"))

      });

      //sauvegarder dans  une varibale de collection
    }
  });


  postman[Request]({
    name: "get brands by id",
    id: "4c52a25d-83bf-4f8c-9ffd-760f3cc41602",
    method: "GET",
    address: "{{url}}/brands/{{id_brand}}",
    post(response) {
      pm.test("Status code get by id is 200", function () {
        pm.response.to.have.status(200);
      });
      pm.test("Response time get by id is less than 250ms", function () {
        pm.expect(pm.response.responseTime).to.be.below(250);
      });
    }
  });

   postman[Request]({
    name: "update brands by id",
    id: "4c52a25d-83bf-4f8c-9ffd-760f3cz41602",
    method: "UPDATE",
    address: "{{url}}/brands/{{id_brand}}",
    data: '{\r\n  "name": "{{name_req_update}}",\r\n  "slug": "{{slug_req_update}}"\r\n}',
    //data: JSON.stringify({ name: name_req, slug: slug_req }),
    headers: {
      "Content-Type": "application/json",
      "Accept": "application/json"
    },
    pre() {
      let name_reqs = "name"
      let slug_reqs = "Slug" + Math.floor(Math.random() * (50000 - 1000 + 1)) + 1000
      pm.collectionVariables.set("slug_req_update", name_reqs)
      pm.collectionVariables.set("slug_req_update", slug_reqs)
    },
    post(response) {
      pm.test("Status code update by id is 200", function () {
        pm.response.to.have.status(200);
      });
      pm.test("Response time update by id is less than 250ms", function () {
        pm.expect(pm.response.responseTime).to.be.below(250);
      });
      pm.test("check message", function () {
        pm.expect(pm.response.json().success).to.be.true();
      });      
    }
  });

}
